services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: craftmanship
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    networks:
      - craftmanship-network

networks:
  craftmanship-network:
    driver: bridge
