spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:6969/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 7100
