spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
server:
  port: ${SERVER_PORT:8080}
cors:
  allowed-origins:
    - http://localhost:8080
